spring:
  application:
    name: database_solutions_project
  datasource:
    url: jdbc:mariadb://localhost:3306/tietokantaratkaisut?allowPublicKeyRetrieval=true
    username: project_dbuser
    password: userpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
